name: Build and test "CAN MESSAGES" component

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    name: Build the source code and run Tests(GoogleTest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: install prerequisites
        run: sudo apt-get -y install python3 python3-pip
      - name: build the code
        run: echo "My python3"
      - name: run tests
        run: echo "Testing run"