name: Build and test "File IO" component

on:
  push:
    branches:
      - master
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    name: Build the source code and run Tests(GoogleTest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: install prerequisites
        run: sudo apt-get install -y cmake build-essential
      - name: build the code
        run: |
          mkdir build 
          cd build
          cmake ../File_IO
          cmake --build . 
      - name: run tests
        run: ./build/lib_ut_tests